#!/bin/bash

function FindOldFolders() {
	folders=($(ls $1 | sort -V | grep '[0-9-]'))
	folders=(${folders[@]/#/"$1/"})
	dirsNum=${#folders[@]}
	[[ $dirsNum -gt $dirsRemainNum ]] && dirsRemoveNum=$(($dirsNum - $dirsRemainNum)) || dirsRemoveNum=0
	echo ${folders[@]:0:$dirsRemoveNum}
}

dst='/mnt/mSATA/data/backups'
dirsRemainNum=7
rm -rf $(FindOldFolders $dst/home)
rm -rf $(FindOldFolders $dst/root)
